import type { Metadata } from "next";
import { Aleo, Lato, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "./(components)/Footer/Footer";
import Navbar from "./(components)/navbar/Navbar";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

const aleo = Aleo({
  variable: "--font-aleo",
  subsets: ["latin"],
});

const lato = Lato({
  weight: ["400"],
  variable: "--font-lato",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="mobile-web-app-capable" content="yes" />
      </head>
      <body
        className={`${montserrat.variable} ${aleo.variable} ${lato.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
