import type { Metadata } from "next";
import { Aleo, Lato, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "./(components)/footer/Footer";
import Navbar from "./(components)/navbar/Navbar";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});

const aleo = Aleo({
  variable: "--font-aleo",
  subsets: ["latin"],
});

const lato = Lato({
  weight: ["400"],
  variable: "--font-lato",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserrat.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
